### PR TITLE
Update for api v5.1

### LINKED ISSUE #34: Suddenly JSONDecodeError
Suddenly, at 2020-05-05 16:11:45 UTC, home assistant stopped being able to track my garage door. I find this in its log:

```
2020-05-05 09:11:45 ERROR (MainThread) [homeassistant.components.myq] Unexpected error fetching myq devices data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 136, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 140, in update_device_info
    "get", "Accounts/{0}/Devices".format(self.account_id)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 83, in request
    data = await resp.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Using the simple "To get all MyQ devices associated with an account" test from the README fails the same way:

```
Traceback (most recent call last):
  File "testmyq.py", line 22, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "testmyq.py", line 11, in main
    myq = await pymyq.login('myqdevice@mydomain.com', 'xxx', websession)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 167, in login
    await api.authenticate(username, password)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 124, in authenticate
    await self.update_device_info()
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 140, in update_device_info
    "get", "Accounts/{0}/Devices".format(self.account_id)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 83, in request
    data = await resp.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### PR DESCRIPTION
**Pull request by bdraco**
Add constants that are currently living in
Home Assistant and should be in this package.

Fixes #34

### CODE REVIEW

**Comment by dseven** [comment]
Applied the patch in my home assistant container. It works!

**Comment by FlyingDiver** [comment]
Could you briefly describe the exact changes you needed to make in the requests to the MyQ servers?  I'm having a hard time telling from the code changes what you actually needed to do.

I have a different (not Home Assistant) setup that is (loosely) based on this code.  So I need to migrate your 5.1 changes to my setup.

**Comment by FlyingDiver** [comment]
Oh, wait, I think I see.  You need to use ".../api/v5/..." for the authentication and account info calls, but ".../api/v5.1/..." for the device specific calls.

**Comment by jcollas** [comment]
The patch works fine for me.  Much appreciated.

**Comment by broyuken** [comment]
This didn't work for me. I had removed the MyQ integration to see if that caused the issue, now when I click on it to re-add it, it just goes back to the list of integrations instead of giving me the login prompt to finish configuring it.

**Comment by bdraco** [comment]
@ehendrix23 Sorry to bother, it looks like you've been doing the merges.

**Comment by broyuken** [comment]
I just replaced those 3 files in my container, anything else I need to do to get this working?

**Comment by kongeng** [comment]
yes, replaced the 3 files in the container and restart.  I had to remove and add the myq integration back because i had changed my password.

**Comment by broyuken** [comment]
Yea that doesn’t work for me, it just kicks me back to the list of integrations. 

edit, I did a dumb. copy/paste error in vi. It's working great now, thank you!

**Comment by KosmixLB** [comment]
It's working me as well. Thanks so much!!

**Review by Knoxie — APPROVED** [review]

**Comment by untergeek** [comment]
Oh, thank you. Please merge and publish this to PyPi. I'd rather do a `pip install -U` than manually patch files.

**Comment by bperkins011** [comment]
Copied the 3 files, restarted, works for me too. Thanks!

**Comment by garyak** [comment]
Copied the api.py, const.py, and device.py file and replaced existing files. Restarted, but still unavailable.

**Comment by tjuel** [comment]
As a HA noob, can you help describe how I can get to the api through the home assistant frontend? Or do I have to access via CLI? I'm not a programmer so apologies in advance.

**Comment by dasb00ter** [comment]
> As a HA noob, can you help describe how I can get to the api through the home assistant frontend? Or do I have to access via CLI? I'm not a programmer so apologies in advance.

Well as a non noob I thought you could just drop these [https://github.com/bdraco/pymyq.git](url) a custom components folder and away you go but I get an unexpected error when I login and the log is not warning me that I'm using a custom component for myq so I guess I'm not doing it right?

**Comment by dseven** [comment]
I don't mean to be rude, but perhaps those who are not familiar with applying patches could just wait until the fix is released, then update your HA systems as you normally would? If you actually know what you're doing, and believe that the proposed fix is insufficient, those reports may be valuable here.

**Comment by garyak** [comment]
Yes, I'll just wait until the next release. I have other options for actuating my garage doors.

**Comment by dasb00ter** [comment]
> I don't mean to be rude, but perhaps those who are not familiar with applying patches could just wait until the fix is released, then update your HA systems as you normally would? If you actually know what you're doing, and believe that the proposed fix is insufficient, those reports may be valuable here.

I dont think your rude. Your right in that github is a place to troubleshoot and develop. Still the nature of the community that I have experienced is to help, especially if I can help back. Help me to help you so to speak.Well typically patching these files directly is not to my understanding the best practice. I've done the above procedure numerous times to get a good result. I certainly make mistakes though. I get the login prompt and get an error. I'll leave that as feedback for people who know more than me. I certainly wont be replying anymore since I agree chatter to a minimum

**Comment by kyotodesertfox** [comment]
It's possible that your experiencing some sort of authentication issue on MyQ end.

The reason that I suggest this is I received the exact same error when I completely removed the integration and tried to re-add it thinking it was something on my end before learning the issue was resolved via an API update.

But it might not be anything that you're doing, necessarily.

**Comment by dale3h** [comment]
I was able to temporarily apply the patch in Hass.io using the following steps:

1. Login to SSH via [Community SSH & Web Terminal](https://github.com/hassio-addons/addon-ssh) add-on.
1. Execute command `docker exec -it homeassistant /bin/bash`
1. Once inside the `homeassistant` Docker container, execute command `pip install -e git://github.com/bdraco/pymyq.git@v51_update#egg=pymyq`
1. Restart Home Assistant.

This tells `pip` to install directly from the `v51_update` branch of @bdraco's `pymyq` fork. The files should be automatically be overwritten the next time Home Assistant is updated.

**Comment by nikiyao** [comment]
@dale3h I can't seem to get this to work I keep getting 

```
bash: docker: command not found
```

**Comment by dale3h** [comment]
@nikiyao Which version of the [***Community*** SSH & Web Terminal add-on](https://github.com/hassio-addons/addon-ssh) do you have installed on your Hass.io system?

**Comment by nikiyao** [comment]
@dale3h 8.5.4

**Comment by dale3h** [comment]
@nikiyao That's the ***Official*** SSH & Terminal add-on. The patching process I described above requires the ***Community*** SSH & Web Terminal add-on, which can be installed from the Add-on Store on your Supervisor panel, under the **Home Assistant Community Add-ons** section.

**Comment by nikiyao** [comment]
Oh ok thanks

**Comment by rct** [comment]
@nikiyao last I checked you also need to disable "protected mode" in order to have access to docker. Note: you'll get some big red warnings when you disable protected mode.

**Comment by kyotodesertfox** [comment]
I used Portainer and was able to skip the Community SSH portion entirely.

I performed the steps suggested by @dale3h; works like a charm!

**Comment by txwindsurfer** [comment]
In the spirit of helping.  Steps by @dale3h worked great but @nikiyao just remember to enter 'login' before executing the docker command in step 2.

> I was able to temporarily apply the patch in Hass.io using the following steps:
> 
> 1. Login to SSH via [Community SSH & Web Terminal](https://github.com/hassio-addons/addon-ssh) add-on.
> 2. Execute command `docker exec -it homeassistant /bin/bash`
> 3. Once inside the `homeassistant` Docker container, execute command `pip install -e git://github.com/bdraco/pymyq.git@v51_update#egg=pymyq`
> 4. Restart Home Assistant.
> 
> This tells `pip` to install directly from the `v51_update` branch of @bdraco's `pymyq` fork. The files should be automatically be overwritten the next time Home Assistant is updated.

**Comment by nikiyao** [comment]
@dale3h that worked great thank you

**Comment by dale3h** [comment]
@txwindsurfer I am not sure that the `login` command applies when using the Community SSH & Web Terminal add-on. In my experience, you only have to type the `login` command when connecting directly to the root filesystem of HassOS.

**Comment by txwindsurfer** [comment]
You are correct, removed my post

**Comment by msauto** [comment]
Confirmed fix dale3h , thanks so much for taking the time to let every one know!!!

**Comment by itzalgd24** [comment]
I used Portainer as well, back up and running here. Thanks @dale3h !

**Comment by codydaig** [comment]
Patch tested on Python 3.6 and works great.

**Comment by csriebel08** [comment]
Thanks! Confirmed worked for me as well.  Thanks for the hard work!

**Comment by dasb00ter** [comment]
Fix included in 0.109.6 thanks a bunch bdraco

**Comment by tkdk1cks** [comment]
STill cant get this to work.

**Comment by dasb00ter** [comment]
> STill cant get this to work.

Probably changed there api again was working for me with this fix now down again in the last couple of days

**Comment by txwindsurfer** [comment]
Fixed in latest release:

https://github.com/home-assistant/core/releases/tag/0.110.5

**Pull request merged**
