### PR TITLE
myq now requires a user agent

### LINKED ISSUE #38: API Changed Again?
Started getting this error today. 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/myq/config_flow.py", line 50, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/usr/src/homeassistant/homeassistant/components/myq/config_flow.py", line 30, in validate_input
    await pymyq.login(data[CONF_USERNAME], data[CONF_PASSWORD], websession)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 170, in login
    await api.authenticate(username, password)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 119, in authenticate
    self._security_token = auth_resp["SecurityToken"]
TypeError: 'NoneType' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by bdraco**
Fixes #38

### CODE REVIEW

**Comment by dseven** [comment]
Confirm this fixes today's issue for me - thanks!

**Comment by NickNothom** [comment]
I updated via pip and I'm still having the same issue as before. Any ideas?
Rebooted everything, and I confirmed that the update worked. 

```
Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/myq/config_flow.py", line 50, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/usr/src/homeassistant/homeassistant/components/myq/config_flow.py", line 30, in validate_input
    await pymyq.login(data[CONF_USERNAME], data[CONF_PASSWORD], websession)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 170, in login
    await api.authenticate(username, password)
  File "/usr/local/lib/python3.7/site-packages/pymyq/api.py", line 119, in authenticate
    self._security_token = auth_resp["SecurityToken"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by bdraco** [comment]
There hasn’t been a new release yet so the change has to be patched in manually at this time

**Comment by funkyche** [comment]
> There hasn’t been a new release yet so the change has to be patched in manually at this time

I apologize for the stupidity of this, but I am new to Hassio. What's the best way to manually patch this? Thanks in advance.

**Comment by funkyche** [comment]
> > There hasn’t been a new release yet so the change has to be patched in manually at this time
> 
> I apologize for the stupidity of this, but I am new to Hassio. What's the best way to manually patch this? Thanks in advance.

I should also mention I am running this from a pi.

**Comment by ehendrix23** [comment]
Just pushed new version (2.0.3) to pypi. Will someone be able to update Home Assistant for new version?

**Comment by bdraco** [comment]
Thanks @ehendrix23 PR is here https://github.com/home-assistant/core/pull/36469

**Comment by GaryOkie** [comment]
Just confirming that this fix is working perfectly.  Thanks so much @bdraco !

@NickNothom - I also found that after installing the update via **pip install pymyq==2.0.3**  and restarting HA, that it didn't work.  This is because HA's myq current requirements forces it to use the 2.0.2 version, so the update gets replaced during the restart.

If you can't wait for the next HA release, then probably the easiest means to obtain the fix is to navigate to _/usr/src/homeassistant/homeassistant/components/myq_ and edit the **manifest.json** file to change the version requirements from 2.0.2 to **2.0.3**, then restart.   That will pull the updated pymyq code automatically.  

(Home Assistant users will need to ssh, then run _docker exec -t -i homeassistant /bin/bash_  in order to access the normally inaccessible HA python code).

**Pull request merged**
