### PR TITLE
Myq requires new ua version

### PR DESCRIPTION
**Pull request by bdraco**
Fixes: https://github.com/home-assistant/core/issues/37100

### CODE REVIEW

**Comment by towerhand** [comment]
Thank you for always fixing this integration so quickly.

**Comment by Nealtron** [comment]
At the rate in which this API continues to break, I'm almost wondering if it would be better to move it to HACS so out-of-band patches can be pushed more frequently.

**Comment by sferguson524** [comment]
Changed the 2 lines in the 2 .py files, and we're good to go here

**Comment by dseven** [comment]
I just found this PR after submitting one of my own (https://github.com/arraylabs/pymyq/pull/45). I found that the Android app appears to use "okhttp/3.10.0", which seems like it may be less prone to frequent change?

**Comment by gary-reyes** [comment]
@arraylabs @ehendrix23 
Would it be possible to review this? Its been nearly a week since it was posted.

@bdraco 
Would it be beneficial to consider forking the project?

**Comment by coreyjansen** [comment]
Anyone have an easy way to port this into HACS or edit this file as I am running HASSIO on my Raspberry Pi

**Comment by balloob** [comment]
It's in the new release of Home Assistant that lands tomorrow.

**Pull request merged**
