### PR TITLE
add the guest account support

### PR DESCRIPTION
**Pull request by zhuqf**
read the API accounts for the devices from invitation. fallback to my if no devices are found.

### CODE REVIEW

**Comment by zhuqf** [comment]
I also create a issue for this but have no idea how to link them

**Comment by marcone** [comment]
Saying something like "fixes #49" in the commit message should link them.
This project seems abandoned though.

**Comment by ehendrix23** [comment]
@zhuqf so the change is to get all the devices from all accounts by getting all accounts and then all devices within each account? And if no account found for some reason then fall-back to how it was retrieved before?

**Comment by zhuqf** [comment]
> @zhuqf so the change is to get all the devices from all accounts by getting all accounts and then all devices within each account? And if no account found for some reason then fall-back to how it was retrieved before?

@ehendrix23 the change allow to read all the devices from current account, no matter the account own the device or not. for example, you can author account  someone@somedomain.com to access your device,  he might have or have not any device himself. someone@somedomain.com login to his account in HA, before change, he could only see his own device in HA, after change he could see both his device and your device in the HA.

Best Regards,
Qiaofeng

**Comment by ehendrix23** [comment]
Version 2.0.7 pushed which includes this fix.

**Pull request merged**
